import test from 'node:test';import assert from 'node:assert/strict';
import {InventoryService} from '../src/services/inventory-service.js';import {calculateStock} from '../src/core/stock.js';import {TRANSACTION_TYPES,BARCODE_FORMATS} from '../src/core/constants.js';import {ScannerService,ZXING_URL} from '../src/services/scanner-service.js';import {qrMatrix,qrSvg} from '../src/services/qr-service.js';import {inventoryCsv} from '../src/services/csv-service.js';
class MemoryRepository{constructor(){this.items=[];this.transactions=[];}async listItems(){return this.items;}async getItem(id){return this.items.find(item=>item.id===Number(id));}async findItemByCode(code){return this.items.find(item=>item.code===code);}async saveItem(item){if(!item.id)item.id=this.items.length+1;this.items=this.items.filter(old=>old.id!==item.id).concat(structuredClone(item));return item.id;}async listTransactions(){return this.transactions;}async applyStockTransaction(id,type,quantity,note=''){const item=await this.getItem(id);const before=item.stock,after=calculateStock(before,type,quantity);item.stock=after;this.transactions.unshift({id:this.transactions.length+1,itemId:id,itemCode:item.code,itemName:item.name,type,quantity,stockBefore:before,stockAfter:after,note,createdAt:new Date().toISOString()});return item;}}
const item=(extra={})=>({code:'8991234567890',codeType:'product',name:'Indomie Goreng',category:'Makanan',unit:'Bungkus',location:'Gudang A',stock:100,minimumStock:20,active:true,...extra});
test('tambah barang dan cari berdasarkan kode scan',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);const saved=await service.saveItem(item());assert.equal(saved.id,1);assert.equal((await service.findActiveItem(' 8991234567890 ')).name,'Indomie Goreng');});
test('edit barang mempertahankan ID dan memperbarui data',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);const saved=await service.saveItem(item());const edited=await service.saveItem({...saved,name:'Indomie Goreng Spesial'});assert.equal(edited.id,saved.id);assert.equal((await repo.listItems()).length,1);assert.equal(edited.name,'Indomie Goreng Spesial');});
test('kode duplikat ditolak',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);await service.saveItem(item());await assert.rejects(()=>service.saveItem(item({name:'Duplikat'})),/sudah digunakan/);});
test('barang tidak ditemukan dan hasil scan dapat dipakai mendaftar',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);assert.equal(await service.findActiveItem('12345670'),null);const saved=await service.saveItem(item({code:'12345670',name:'Hasil Scan'}));assert.equal(saved.code,'12345670');});
test('generate kode dan QR hanya memakai identifier',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);repo.items=[item({id:1,code:'BRG-00009',codeType:'generated'})];assert.equal(await service.nextGeneratedCode(),'BRG-00010');assert.equal(qrMatrix('BRG-00010').length,21);assert.match(qrSvg('BRG-00010'),/<svg/);assert.doesNotMatch(qrSvg('BRG-00010'),/stock/i);});
test('stok masuk, keluar dan penyesuaian dihitung benar',()=>{assert.equal(calculateStock(100,TRANSACTION_TYPES.IN,20),120);assert.equal(calculateStock(100,TRANSACTION_TYPES.OUT,20),80);assert.equal(calculateStock(100,TRANSACTION_TYPES.ADJUSTMENT,55),55);});
test('stok keluar melebihi stok ditolak dengan pesan jelas',()=>assert.throws(()=>calculateStock(5,TRANSACTION_TYPES.OUT,10),/Stok tidak mencukupi/));
test('transaksi mencatat stok sebelum, sesudah dan riwayat',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);const saved=await service.saveItem(item());await repo.applyStockTransaction(saved.id,'IN',5,'Barang datang');const [tx]=await repo.listTransactions();assert.deepEqual([tx.stockBefore,tx.stockAfter,tx.quantity,tx.note],[100,105,5,'Barang datang']);});
test('dashboard menghitung stok, menipis dan habis',async()=>{const repo=new MemoryRepository(),service=new InventoryService(repo);repo.items=[item({id:1,stock:100}),item({id:2,code:'B',stock:10}),item({id:3,code:'C',stock:0})];const dashboard=await service.dashboard();assert.deepEqual([dashboard.totalItems,dashboard.totalStock,dashboard.low.length,dashboard.empty.length],[3,110,1,1]);});
test('CSV memiliki seluruh kolom dan escaping',()=>{const csv=inventoryCsv([item({name:'Kopi, Susu'})]);assert.match(csv,/"Kode","Nama"/);assert.match(csv,/"Kopi, Susu"/);assert.match(csv,/"AMAN"/);});
test('scanner meminta QR dan format barcode produk umum',()=>{for(const format of ['qr_code','ean_13','ean_8','upc_a','code_128','code_39'])assert.ok(BARCODE_FORMATS.includes(format));assert.match(ZXING_URL,/@zxing\/browser@0\.1\.5/);});
test('proteksi double scan menolak kode sama dalam cooldown',()=>{const received=[],scanner=new ScannerService(null,value=>received.push(value));const realNow=Date.now;let now=1000;Date.now=()=>now;scanner.emit('EAN-1');now=1200;scanner.emit('EAN-1');scanner.emit('EAN-2');Date.now=realNow;assert.deepEqual(received,['EAN-1','EAN-2']);});
