import { TX, stockStatus, nextGeneratedCode, filterTransactions, inventoryCsv, dashboardStats, filterInventory, inventoryReportStats } from './domain.js';
import { InventoryRepository } from './repository.js';
import { BarcodeScanner, SCANNER_STATE } from './scanner.js';
import { buildImportBatch, createReportWorkbook, createTemplateWorkbook, validateImportHeaders, validateImportRows, workbookRows } from './excel.js';
const repo=new InventoryRepository(), scanner=new BarcodeScanner();
scanner.subscribe(updateCameraStatus);
const app=document.querySelector('#app'), modalRoot=document.querySelector('#modal-root');
const pages=[['dashboard','Dashboard','⌂','Dashboard'],['scan','Scan Stock','⌗','Scan'],['items','Master Barang','▦','Barang'],['transactions','Transaksi','⇄','Transaksi'],['reports','Laporan','▤','Laporan'],['import','Import Barang','⇩','Import']];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('id-ID').format(n);
const date=s=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(s));
const time=s=>new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit'}).format(new Date(s));
function nav(){const hash=location.hash.slice(1).split('/')[0]||'dashboard';const links=pages.map(([id,label,icon])=>`<a href="#${id}" class="${hash===id?'active':''}"><span class="nav-icon">${icon}</span><span>${label}</span></a>`).join('');document.querySelector('#side-nav').innerHTML=links;document.querySelector('#bottom-nav').innerHTML=pages.map(([id,,icon,mobile])=>`<a href="#${id}" class="${hash===id?'active':''}"><span class="nav-icon">${icon}</span><span>${mobile}</span></a>`).join('');}
function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className=`show ${error?'error':''}`;setTimeout(()=>el.className='',2600)}
function empty(title='Belum ada data',copy='Tambahkan data untuk mulai menggunakan StokQR.') {return `<div class="empty-state"><b>${title}</b>${copy}</div>`}
function status(i){return `<span class="badge ${stockStatus(i)}">${stockStatus(i)}</span>`}
function header(title){document.querySelector('#page-title').textContent=title;document.querySelector('#breadcrumb').textContent=title.toUpperCase();}
const yieldToUi=()=>new Promise(resolve=>setTimeout(resolve));
function downloadBlob(content,name,type='text/plain;charset=utf-8'){const blob=content instanceof Blob?content:new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function excelLibrary(){if(!globalThis.XLSX)throw new Error('Library Excel belum tersedia. Sambungkan internet lalu muat ulang.');return globalThis.XLSX}
async function dashboard(){header('Dashboard');const items=await repo.allItems(), txs=await repo.allTransactions(),s=dashboardStats(items);const low=items.filter(i=>stockStatus(i)==='MENIPIS'),out=items.filter(i=>stockStatus(i)==='HABIS');app.innerHTML=`<section class="hero"><div><h2>Selamat datang di StokQR</h2><p>Pantau kondisi gudang Anda dalam satu tampilan.</p></div><button class="btn primary" data-go="scan">⌗ Scan Barang</button></section><section class="stats">${[['TOTAL BARANG',s.totalItems,'▦',''],['TOTAL STOK',money(s.totalStock),'▤',''],['STOK MENIPIS',s.low,'!','low'],['STOK HABIS',s.empty,'×','empty']].map(x=>`<article class="card stat ${x[3]}"><div class="stat-top"><span>${x[0]}</span><span>${x[2]}</span></div><strong>${x[1]}</strong></article>`).join('')}</section><section class="grid-2"><article class="card panel"><h3>Transaksi Terbaru</h3>${txs.length?txs.slice(0,6).map(t=>`<div class="list-row"><div><b>${esc(t.itemName)}</b><small>${date(t.createdAt)} · ${time(t.createdAt)}</small></div><div><b>${t.type===TX.OUT?'-':'+'}${Math.abs(t.amount)}</b><small>${esc(t.type)}</small></div></div>`).join(''):empty('Belum ada transaksi')}</article><div class="stack"><article class="card panel"><h3>Barang Stok Menipis</h3>${low.length?low.slice(0,4).map(i=>rowItem(i)).join(''):empty('Semua stok aman')}</article><article class="card panel"><h3>Barang Stok Habis</h3>${out.length?out.slice(0,4).map(i=>rowItem(i)).join(''):empty('Tidak ada stok habis')}</article></div></section>`;}
const rowItem=i=>`<div class="list-row"><div><b>${esc(i.name)}</b><small>${esc(i.code)} · ${esc(i.location)}</small></div><div><b>${i.stock} ${esc(i.unit)}</b><br>${status(i)}</div></div>`;
async function itemsPage(){header('Master Barang');const items=await repo.allItems();app.innerHTML=`<section class="hero"><div><h2>Master Barang</h2><p>Kelola identitas dan persediaan barang gudang.</p></div><button class="btn primary" id="add-item">＋ Tambah Barang</button></section><article class="card panel"><div class="toolbar"><input id="item-search" placeholder="Cari nama atau kode..."><select id="item-filter"><option value="all">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option><option value="low">Menipis / Habis</option></select><button class="btn outline" id="demo">Isi Data Demo</button></div><div class="table-wrap" id="items-table"></div></article>`;const render=()=>{const q=document.querySelector('#item-search').value.toLowerCase(),f=document.querySelector('#item-filter').value;const rows=items.filter(i=>(`${i.name} ${i.code}`.toLowerCase().includes(q))&&(f==='all'||f==='active'&&i.active||f==='inactive'&&!i.active||f==='low'&&stockStatus(i)!=='AMAN'));document.querySelector('#items-table').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Barang</th><th>Kategori</th><th>Lokasi</th><th>Stok</th><th>Status</th><th>Aktif</th></tr></thead><tbody>${rows.map(i=>`<tr data-id="${i.id}"><td><b>${esc(i.name)}</b><br><small>${esc(i.code)}</small></td><td>${esc(i.category)}</td><td>${esc(i.location)}</td><td><b>${i.stock}</b> ${esc(i.unit)}</td><td>${status(i)}</td><td>${i.active?'Ya':'Tidak'}</td></tr>`).join('')}</tbody></table>`:empty()};render();document.querySelector('#item-search').oninput=render;document.querySelector('#item-filter').onchange=render;document.querySelector('#add-item').onclick=()=>itemForm();document.querySelector('#demo').onclick=seedDemo;document.querySelector('#items-table').onclick=e=>{const tr=e.target.closest('[data-id]');if(tr)location.hash=`item/${tr.dataset.id}`};}
async function itemForm(prefill={},options={}){await scanner.stop();const existing=prefill.id?await repo.getItem(prefill.id):null;const v=existing||prefill;modalRoot.innerHTML=`<div class="modal-backdrop"><form class="modal" id="item-form"><h2>${existing?'Edit':'Tambah'} Barang</h2><div class="form-grid"><label class="span-2"><span>Kode Barang *</span><div class="toolbar"><input name="code" required value="${esc(v.code||'')}"><button type="button" class="btn" id="generate-code">Buat Kode</button></div></label><label class="span-2"><span>Nama Barang *</span><input name="name" required value="${esc(v.name||'')}"></label><label><span>Kategori</span><input name="category" value="${esc(v.category||'')}"></label><label><span>Satuan</span><input name="unit" value="${esc(v.unit||'PCS')}"></label><label><span>Lokasi Gudang</span><input name="location" value="${esc(v.location||'Gudang A')}"></label><label><span>Stok Minimum</span><input name="minimum" type="number" min="0" value="${v.minimum??0}"></label><label><span>${existing?'Stok dikelola via transaksi':'Stok Awal'}</span><input name="stock" type="number" min="0" value="${v.stock??0}" ${existing?'disabled':''}></label><label><span>Status</span><select name="active"><option value="true" ${v.active!==false?'selected':''}>Aktif</option><option value="false" ${v.active===false?'selected':''}>Nonaktif</option></select></label><label class="span-2"><span>Foto (URL atau data URL)</span><input name="photo" value="${esc(v.photo||'')}"></label></div><div class="modal-actions"><button type="button" class="btn" data-close>Batal</button><button class="btn primary">Simpan Barang</button></div></form></div>`;document.querySelector('[data-close]').onclick=async()=>{closeModal();if(options.returnToScan)await render()};document.querySelector('#generate-code').onclick=async()=>{const input=document.querySelector('[name=code]');input.value=nextGeneratedCode(await repo.allItems());input.dataset.generated='true'};document.querySelector('#item-form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{await repo.saveItem({...existing,...o,stock:existing?.stock??Number(o.stock),minimum:Number(o.minimum),active:o.active==='true',generated:e.target.code.dataset.generated==='true'||existing?.generated});closeModal();toast('Barang berhasil disimpan.');if(options.returnToScan){location.hash='scan';await render()}else{location.hash='items';await render()}}catch(err){toast(err.message,true)}};}
function closeModal(){modalRoot.innerHTML=''}
const CAMERA_STATUS={
  [SCANNER_STATE.IDLE]:['Kamera belum aktif','Tekan tombol mulai untuk memindai'],
  [SCANNER_STATE.STARTING]:['Mengaktifkan kamera...','Mohon tunggu dan izinkan akses kamera'],
  [SCANNER_STATE.SCANNING]:['Kamera aktif — mencari barcode...','Arahkan barcode ke dalam bingkai'],
  [SCANNER_STATE.DETECTED]:['Barcode terbaca','Sedang mencari data barang'],
  [SCANNER_STATE.ERROR]:['Kamera gagal dimulai','Tekan Coba Lagi setelah memeriksa kamera']
};
const CAMERA_ERROR_TITLES={PERMISSION_DENIED:'Izin kamera ditolak',CAMERA_BUSY:'Kamera sedang digunakan',CAMERA_UNAVAILABLE:'Kamera tidak tersedia',MEDIA_API_UNSUPPORTED:'Akses kamera tidak didukung',DECODER_UNAVAILABLE:'Scanner tidak dapat dimuat',VIDEO_ELEMENT_MISSING:'Tampilan kamera bermasalah',SCANNER_RUNTIME_ERROR:'Scanner berhenti',CAMERA_ERROR:'Kamera gagal dibuka'};
function updateCameraStatus(state,detail){const camera=document.querySelector('.camera'),status=document.querySelector('#camera-status'),button=document.querySelector('#start-camera');if(!camera||!status)return;const base=CAMERA_STATUS[state]||CAMERA_STATUS[SCANNER_STATE.IDLE],copy=state===SCANNER_STATE.ERROR?[CAMERA_ERROR_TITLES[detail?.code]||base[0],detail?.message||base[1]]:base;status.innerHTML=`<b>${esc(copy[0])}</b><p>${esc(copy[1])}</p>`;camera.dataset.scannerState=state;camera.classList.toggle('is-scanning',state===SCANNER_STATE.SCANNING);if(button){button.disabled=state===SCANNER_STATE.STARTING||state===SCANNER_STATE.SCANNING;button.textContent=state===SCANNER_STATE.ERROR?'Coba Lagi':state===SCANNER_STATE.SCANNING?'Kamera Aktif':'Mulai Kamera'}}
async function scanPage(){await scanner.stop();header('Scan Stock');app.innerHTML=`<section class="hero"><div><h2>Scan Barcode / QR</h2><p>Arahkan kamera belakang ke barcode produk atau QR StokQR.</p></div></section><section class="scanner-layout"><div class="camera" data-scanner-state="idle"><video id="video" autoplay muted playsinline></video><div class="camera-copy" id="camera-status" role="status" aria-live="polite"><b>Kamera belum aktif</b><p>Tekan tombol mulai untuk memindai</p></div><div class="scan-frame"><span class="scan-line"></span></div><div class="camera-actions"><button class="btn primary" id="start-camera">Mulai Kamera</button><button class="btn" id="manual">Input Kode</button></div></div><article class="card scan-result" id="scan-result">${empty('Siap memindai','Mendukung QR, EAN-13, EAN-8, UPC-A, Code 128, dan Code 39.')}</article></section>`;updateCameraStatus(SCANNER_STATE.IDLE);document.querySelector('#start-camera').onclick=startCamera;document.querySelector('#manual').onclick=async()=>{const code=prompt('Masukkan kode barcode / QR');if(code){await scanner.stop({preserveState:true});updateCameraStatus(SCANNER_STATE.DETECTED,code);await handleScan(code)}};}
async function startCamera(){const video=document.querySelector('#video');if(!video)return;scanner.prepareFeedback();try{await scanner.start(video,handleScan,error=>updateCameraStatus(SCANNER_STATE.ERROR,error))}catch(error){updateCameraStatus(SCANNER_STATE.ERROR,error);toast(error.message,true)}}
async function resumeCamera(delay=0){await scanner.stop();if(delay)await new Promise(resolve=>setTimeout(resolve,delay));if(document.querySelector('#video'))await startCamera()}
async function handleScan(raw){updateCameraStatus(SCANNER_STATE.DETECTED,raw);const code=scanner.acceptDecoded(raw),item=await repo.findByCode(code),box=document.querySelector('#scan-result');if(!box)return;if(!item){box.innerHTML=`<p class="eyebrow">BARANG BELUM TERDAFTAR</p><h2>${esc(code)}</h2><p>Kode hasil scan belum ada di database lokal.</p><button class="btn primary" id="register-scan">Daftarkan Barang</button><button class="btn" id="scan-again">Scan Lagi</button>`;document.querySelector('#register-scan').onclick=async()=>{await scanner.stop();await itemForm({code},{returnToScan:true})};document.querySelector('#scan-again').onclick=()=>resumeCamera();return}box.innerHTML=`<p class="eyebrow">BARANG DITEMUKAN</p><h2>${esc(item.name)}</h2><p>Kode: <b>${esc(item.code)}</b></p><div class="detail-cell"><small>Stok saat ini</small><b style="font-size:28px">${item.stock} ${esc(item.unit)}</b></div><div class="qty"><button data-minus>−</button><input id="scan-qty" type="number" min="1" value="1"><button data-plus>＋</button></div><div class="quick"><button class="btn" data-qty="1">+1</button><button class="btn" data-qty="5">+5</button><button class="btn" data-qty="10">+10</button></div><div class="stack" style="margin-top:14px"><button class="btn primary" data-tx="${TX.IN}">Tambah Stok</button><button class="btn danger" data-tx="${TX.OUT}">Kurangi Stok</button></div>`;const qty=document.querySelector('#scan-qty');document.querySelector('[data-minus]').onclick=()=>qty.value=Math.max(1,+qty.value-1);document.querySelector('[data-plus]').onclick=()=>qty.value=+qty.value+1;document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>qty.value=b.dataset.qty);document.querySelectorAll('[data-tx]').forEach(b=>b.onclick=async()=>{try{await repo.transact(item.id,b.dataset.tx,+qty.value,'Scan Stock');toast('✓ Stok berhasil diperbarui');box.innerHTML=empty('Transaksi berhasil','Kamera disiapkan untuk barang berikutnya…');await resumeCamera(700)}catch(e){toast(e.message,true)}})}
async function transactionsPage(){header('Transaksi');const rows=await repo.allTransactions();app.innerHTML=`<section class="hero"><div><h2>Riwayat Transaksi</h2><p>Jejak setiap perubahan stok tersimpan otomatis.</p></div></section><article class="card panel"><div class="toolbar"><input id="tx-search" placeholder="Cari nama atau kode..."><select id="tx-period"><option value="today">Hari ini</option><option value="7days">7 hari</option><option value="month">Bulan ini</option><option value="all">Semua</option></select></div><div class="table-wrap" id="tx-table"></div></article>`;const draw=()=>{const data=filterTransactions(rows,document.querySelector('#tx-period').value,document.querySelector('#tx-search').value);document.querySelector('#tx-table').innerHTML=data.length?`<table class="data-table"><thead><tr><th>Tanggal / Jam</th><th>Barang</th><th>Jenis</th><th>Jumlah</th><th>Sebelum</th><th>Sesudah</th><th>Catatan</th></tr></thead><tbody>${data.map(t=>`<tr><td>${date(t.createdAt)}<br><small>${time(t.createdAt)}</small></td><td><b>${esc(t.itemName)}</b><br><small>${esc(t.code)}</small></td><td>${esc(t.type)}</td><td>${t.amount>0?'+':''}${t.amount}</td><td>${t.before}</td><td>${t.after}</td><td>${esc(t.note||'-')}</td></tr>`).join('')}</tbody></table>`:empty('Transaksi tidak ditemukan')};draw();document.querySelector('#tx-search').oninput=draw;document.querySelector('#tx-period').onchange=draw;}
async function reportsPage(){
  header('Laporan Stok');const items=await repo.allItems();const categories=[...new Set(items.map(i=>i.category))].sort(),locations=[...new Set(items.map(i=>i.location))].sort();
  app.innerHTML=`<section class="hero report-hero no-print"><div><h2>Laporan Stok</h2><p>Laporan inventory yang dapat difilter, diexport, dan dicetak.</p></div><div class="report-actions"><button class="btn primary" id="export-xlsx">⇩ Export Excel</button><button class="btn outline" id="export-csv">Export CSV</button><button class="btn" id="print-report">Cetak / Print</button></div></section><article class="card panel report-filters no-print"><div class="filter-grid"><input id="report-query" placeholder="Cari kode atau nama barang"><select id="report-active"><option value="all">Semua Barang</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><select id="report-category"><option value="all">Semua Kategori</option>${categories.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select><select id="report-location"><option value="all">Semua Lokasi</option>${locations.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select><select id="report-status"><option value="all">Semua Status Stok</option><option value="AMAN">AMAN</option><option value="MENIPIS">MENIPIS</option><option value="HABIS">HABIS</option></select></div></article><section id="print-report-area"><div class="print-title"><b>STOKQR</b><h2>LAPORAN STOK GUDANG</h2><p id="print-date"></p><p id="print-filters"></p></div><section class="stats report-stats" id="report-stats"></section><article class="card panel report-table-card"><div id="report-table"></div></article></section>`;
  const currentFilters=()=>({query:document.querySelector('#report-query').value,active:document.querySelector('#report-active').value,category:document.querySelector('#report-category').value,location:document.querySelector('#report-location').value,status:document.querySelector('#report-status').value});
  const filterLabel=filters=>[`Barang: ${filters.active==='all'?'Semua':filters.active==='active'?'Aktif':'Nonaktif'}`,`Kategori: ${filters.category==='all'?'Semua':filters.category}`,`Lokasi: ${filters.location==='all'?'Semua':filters.location}`,`Status: ${filters.status==='all'?'Semua':filters.status}`,filters.query?`Pencarian: ${filters.query}`:''].filter(Boolean).join(' · ');
  let filtered=[];const draw=()=>{const filters=currentFilters();filtered=filterInventory(items,filters);const stats=inventoryReportStats(filtered);document.querySelector('#report-stats').innerHTML=[['TOTAL JENIS BARANG',stats.totalItems,''],['TOTAL STOK',money(stats.totalStock),''],['STOK AMAN',stats.safe,''],['STOK MENIPIS',stats.low,'low'],['STOK HABIS',stats.empty,'empty']].map(([label,value,kind])=>`<article class="card stat ${kind}"><div class="stat-top"><span>${label}</span></div><strong>${value}</strong></article>`).join('');document.querySelector('#print-date').textContent=`Tanggal laporan: ${new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeStyle:'short'}).format(new Date())}`;document.querySelector('#print-filters').textContent=`Filter: ${filterLabel(filters)}`;document.querySelector('#report-table').innerHTML=filtered.length?`<div class="table-wrap report-desktop"><table class="data-table report-table"><thead><tr><th>No</th><th>Kode</th><th>Nama Barang</th><th>Kategori</th><th>Lokasi</th><th>Stok</th><th>Satuan</th><th>Minimum</th><th>Status</th><th>Terakhir Diperbarui</th></tr></thead><tbody>${filtered.map((i,index)=>`<tr><td>${index+1}</td><td>${esc(i.code)}</td><td><b>${esc(i.name)}</b></td><td>${esc(i.category)}</td><td>${esc(i.location)}</td><td><b>${i.stock}</b></td><td>${esc(i.unit)}</td><td>${i.minimum}</td><td>${status(i)}</td><td>${i.updatedAt?date(i.updatedAt):'-'}</td></tr>`).join('')}</tbody></table></div><div class="report-mobile">${filtered.map(i=>`<article class="inventory-card"><div><b>${esc(i.name)}</b><small>${esc(i.code)}</small></div><dl><div><dt>Stok</dt><dd>${i.stock} ${esc(i.unit)}</dd></div><div><dt>Minimum</dt><dd>${i.minimum}</dd></div><div><dt>Lokasi</dt><dd>${esc(i.location)}</dd></div><div><dt>Status</dt><dd>${status(i)}</dd></div></dl></article>`).join('')}</div>`:empty('Data laporan tidak ditemukan','Ubah filter atau tambahkan barang terlebih dahulu.')};
  document.querySelectorAll('.filter-grid input,.filter-grid select').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',draw));draw();
  document.querySelector('#export-csv').onclick=()=>{downloadBlob('\ufeff'+inventoryCsv(filtered),`laporan-stok-${new Date().toISOString().slice(0,10)}.csv`,'text/csv;charset=utf-8');toast('Laporan berhasil diexport.')};
  document.querySelector('#export-xlsx').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='Membuat Excel...';try{await yieldToUi();const XLSX=excelLibrary(),wb=createReportWorkbook(XLSX,filtered,filterLabel(currentFilters()));XLSX.writeFile(wb,`laporan-stok-${new Date().toISOString().slice(0,10)}.xlsx`);toast('Laporan berhasil diexport.')}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='⇩ Export Excel'}};
  document.querySelector('#print-report').onclick=()=>print();
}

async function importPage(){
  header('Import Barang');let validation=null;
  app.innerHTML=`<section class="hero"><div><h2>Import Barang</h2><p>Import banyak barang sekaligus menggunakan template StokQR.</p></div></section><section class="grid-2 import-layout"><article class="card panel"><h3>1. Siapkan file Excel</h3><p class="muted">Gunakan template agar nama kolom dan format data sesuai.</p><button class="btn primary" id="download-template">⇩ Download Template Excel</button></article><article class="card panel"><h3>2. Pilih file</h3><label class="file-picker"><span>Pilih File Excel (.xlsx/.xls)</span><input id="excel-file" type="file" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel"></label><p class="muted">File diproses lokal di perangkat dan tidak dikirim ke server.</p></article></section><div id="import-progress" class="progress-card card" hidden><div><b id="progress-label">Membaca file...</b><span id="progress-value">0%</span></div><progress id="progress-bar" max="100" value="0"></progress></div><section id="import-preview"></section>`;
  const progress=(label,value)=>{const wrap=document.querySelector('#import-progress');wrap.hidden=false;document.querySelector('#progress-label').textContent=label;document.querySelector('#progress-value').textContent=`${value}%`;document.querySelector('#progress-bar').value=value};
  document.querySelector('#download-template').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='Membuat template...';try{await yieldToUi();const XLSX=excelLibrary();XLSX.writeFile(createTemplateWorkbook(XLSX),'template-import-stokqr.xlsx');toast('Template berhasil dibuat.')}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='⇩ Download Template Excel'}};
  document.querySelector('#excel-file').onchange=async e=>{const file=e.target.files?.[0];validation=null;if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['xlsx','xls'].includes(ext)){toast('Pilih file Excel .xlsx atau .xls.',true);e.target.value='';return}if(file.size>10*1024*1024){toast('Ukuran file maksimal 10 MB.',true);e.target.value='';return}try{progress('Membaca file...',15);await yieldToUi();const XLSX=excelLibrary(),buffer=await file.arrayBuffer();progress('Memvalidasi data...',55);await yieldToUi();const workbook=XLSX.read(buffer,{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]],headers=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''})[0]||[],headerCheck=validateImportHeaders(headers);if(!headerCheck.valid)throw new Error(`Header tidak lengkap: ${headerCheck.missing.join(', ')}.`);const rows=workbookRows(XLSX,workbook),existing=await repo.allItems();validation=validateImportRows(rows,existing);progress('Validasi selesai.',100);renderImportPreview(validation);toast('File berhasil dibaca. Validasi selesai.')}catch(error){validation=null;document.querySelector('#import-preview').innerHTML=`<article class="card panel import-error"><h3>File tidak dapat diproses</h3><p>${esc(error.message)}</p></article>`;progress('Validasi gagal',100);toast(error.message,true)}};
  function renderImportPreview(result){const badges=[['Total baris',result.total,''],['Valid',result.valid,'valid'],['Warning',result.warning,'warning'],['Error',result.error,'error']];document.querySelector('#import-preview').innerHTML=`<section class="import-summary">${badges.map(([label,value,kind])=>`<article class="card ${kind}"><span>${label}</span><strong>${value}</strong></article>`).join('')}</section>${result.fatal?`<article class="card panel import-error"><b>${esc(result.fatal)}</b></article>`:''}<article class="card panel"><div class="preview-head"><div><h3>Preview Validasi</h3><p class="muted">Baris warning dan error tidak akan dimasukkan.</p></div><button class="btn outline" id="download-validation">Download Hasil Validasi</button></div><div class="table-wrap"><table class="data-table preview-table"><thead><tr><th>Baris</th><th>Kode</th><th>Nama Barang</th><th>Status</th><th>Keterangan</th></tr></thead><tbody>${result.rows.map(row=>`<tr><td>${row.rowNumber}</td><td>${esc(row.code||'-')}</td><td>${esc(row.name||'-')}</td><td><span class="validation-badge ${row.level}">${row.level==='valid'?'✓ Valid':row.level==='warning'?'⚠ Warning':'✕ Error'}</span></td><td>${esc(row.messages.join('; ')||'-')}</td></tr>`).join('')}</tbody></table></div><div class="import-actions"><button class="btn primary" id="import-data" ${result.canImport?'':'disabled'}>Import Data (${result.valid})</button></div></article>`;document.querySelector('#download-validation').onclick=()=>{const csv=['Baris,Kode,Nama Barang,Status,Keterangan',...result.rows.map(row=>[row.rowNumber,row.code,row.name,row.level,row.messages.join('; ')].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','))].join('\n');downloadBlob('\ufeff'+csv,'hasil-validasi-import.csv','text/csv;charset=utf-8')};const importButton=document.querySelector('#import-data');importButton.onclick=async()=>{const batch=buildImportBatch(result);if(!batch.length)return;importButton.disabled=true;try{progress('Mengimport data...',75);await yieldToUi();const imported=await repo.importItems(batch);progress('Import selesai.',100);toast('Import berhasil.');document.querySelector('#import-preview').innerHTML=`<article class="card panel import-complete"><h2>Import selesai</h2><dl><div><dt>Total baris</dt><dd>${result.total}</dd></div><div><dt>Berhasil</dt><dd>${imported.length}</dd></div><div><dt>Warning</dt><dd>${result.warning}</dd></div><div><dt>Gagal</dt><dd>${result.error}</dd></div></dl><button class="btn primary" data-go="items">Lihat Master Barang</button></article>`}catch(error){toast(error.message,true);importButton.disabled=false;progress('Import gagal',100)}};}
}
async function itemDetail(id){const i=await repo.getItem(id);if(!i){location.hash='items';return}header('Detail Barang');app.innerHTML=`<section class="hero"><div><button class="btn" data-go="items">← Kembali</button></div><div><button class="btn" id="edit">Edit</button> <button class="btn ${i.active?'danger':''}" id="toggle">${i.active?'Nonaktifkan':'Aktifkan'}</button></div></section><article class="card panel"><div class="detail-head"><div class="product-image">${i.photo?`<img class="product-image" src="${esc(i.photo)}" alt="">`:'▦'}</div><div><p class="eyebrow">${esc(i.code)}</p><h2>${esc(i.name)}</h2>${status(i)}</div></div><div class="detail-grid">${[['Stok',`${i.stock} ${i.unit}`],['Minimum',i.minimum],['Kategori',i.category],['Lokasi',i.location],['Status barang',i.active?'Aktif':'Nonaktif'],['Diperbarui',date(i.updatedAt)]].map(x=>`<div class="detail-cell"><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('')}</div><div class="toolbar"><button class="btn primary" data-adjust="${TX.IN}">Tambah Stok</button><button class="btn danger" data-adjust="${TX.OUT}">Kurangi Stok</button><button class="btn" data-go="scan">Scan</button><button class="btn" data-go="transactions">Riwayat</button></div>${i.generated?`<hr><h3>QR Barang</h3><div id="qr" class="qr-box"></div><div class="toolbar"><button class="btn" id="download-qr">Download</button><button class="btn" id="print-qr">Cetak</button><button class="btn" id="share-qr">Bagikan</button></div>`:''}</article>`;document.querySelector('#edit').onclick=()=>itemForm(i);document.querySelector('#toggle').onclick=async()=>{await repo.saveItem({...i,active:!i.active});toast('Status barang diperbarui.');render()};document.querySelectorAll('[data-adjust]').forEach(b=>b.onclick=()=>transactionModal(i,b.dataset.adjust));if(i.generated)makeQr(i);}
function transactionModal(i,type){modalRoot.innerHTML=`<div class="modal-backdrop"><form class="modal" id="tx-form"><h2>${type}</h2><p>${esc(i.name)} · Stok ${i.stock} ${esc(i.unit)}</p><label>Jumlah<input name="amount" type="number" min="1" value="1" required></label><label>Catatan<textarea name="note" rows="3"></textarea></label><div class="modal-actions"><button type="button" class="btn" data-close>Batal</button><button class="btn primary">Simpan Transaksi</button></div></form></div>`;document.querySelector('[data-close]').onclick=closeModal;document.querySelector('#tx-form').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);try{await repo.transact(i.id,type,+d.get('amount'),d.get('note'));closeModal();toast('Stok berhasil diperbarui.');render()}catch(err){toast(err.message,true)}};}
function makeQr(i){const box=document.querySelector('#qr');if(!globalThis.QRCode){box.innerHTML='<p>Generator QR belum tersedia. Sambungkan internet lalu muat ulang.</p>';return}QRCode.toCanvas(i.code,{width:240,margin:2},(e,canvas)=>{if(!e)box.append(canvas)});document.querySelector('#download-qr').onclick=()=>{const a=document.createElement('a');a.download=`QR-${i.code}.png`;a.href=box.querySelector('canvas').toDataURL();a.click()};document.querySelector('#print-qr').onclick=()=>print();document.querySelector('#share-qr').onclick=async()=>{const canvas=box.querySelector('canvas');const blob=await new Promise(r=>canvas.toBlob(r));const file=new File([blob],`QR-${i.code}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]}))navigator.share({title:i.name,text:i.code,files:[file]});else toast('Browser tidak mendukung berbagi file.',true)};}
async function seedDemo(){const all=await repo.allItems();if(all.length&&!confirm('Tambahkan data demo ke data yang sudah ada?'))return;for(const x of [{code:'8991234567890',name:'Indomie Goreng',category:'Makanan',unit:'Bungkus',location:'Gudang A',stock:100,minimum:20},{code:'8996001600269',name:'Aqua 600ml',category:'Minuman',unit:'Botol',location:'Gudang A',stock:8,minimum:10},{code:'BRG-00001',name:'Kopi ABC',category:'Minuman',unit:'Sachet',location:'Rak B',stock:0,minimum:10,generated:true},{code:'8992752111245',name:'Teh Botol',category:'Minuman',unit:'Botol',location:'Rak C',stock:48,minimum:12}])if(!await repo.findByCode(x.code))await repo.saveItem(x);toast('Data demo berhasil ditambahkan.');render()}
async function render(){await scanner.stop();closeModal();nav();const [page,arg]=location.hash.slice(1).split('/');try{if(page==='scan')await scanPage();else if(page==='items')await itemsPage();else if(page==='transactions')await transactionsPage();else if(page==='reports')await reportsPage();else if(page==='import')await importPage();else if(page==='item')await itemDetail(arg);else await dashboard();}catch(e){console.error(e);app.innerHTML=empty('Aplikasi gagal memuat',esc(e.message));}}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)location.hash=go.dataset.go});addEventListener('hashchange',render);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));render();
